apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-pv-0
  namespace: olm
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/elk0"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-pv-1
  namespace: olm
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/elk1"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-pv-2
  namespace: olm
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/elk2"